module.exports = {
  defaultRegion: 'euw',
  defaultLimitPer10s: 10,
  defaultLimitPer10min: 500,
  defaultTTL: 3600,
  endpoint: 'api.pvp.net/api/lol',
  uri: {
    // Champion
    CHAMPION_LIST: '/{region}/v1.2/champion',
    CHAMPION_ID: '/{region}/v1.2/champion/{id}',
    // Game
    RECENT_GAMES: '/{region}/v1.3/game/by-summoner/{id}/recent',
    // League
    LEAGUE_BY_SUMMONER_FULL: '/{region}/v2.5/league/by-summoner/{id}',
    LEAGUE_BY_SUMMONER: '/{region}/v2.5/league/by-summoner/{id}/entry',
    LEAGUE_BY_TEAM_FULL: '/{region}/v2.5/league/by-team/{id}',
    LEAGUE_BY_TEAM: '/{region}/v2.5/league/by-team/{id}/entry',
    CHALLENGER_LEAGUE: '/{region}/v2.5/league/challenger',
    // Match
    MATCH: '/{region}/v2.2/match/{id}',
    // Match history
    MATCH_HISTORY: '/{region}/v2.2/matchhistory/{id}',
    // Summoner
    SUMMONER_BY_NAME: '/{region}/v1.4/summoner/by-name/{names}',
    SUMMONER_ID: '/{region}/v1.4/summoner/{id}',
    SUMMONER_NAME: '/{region}/v1.4/summoner/{id}/name',
    SUMMONER_RUNES: '/{region}/v1.4/summoner/{id}/runes',
    SUMMONER_MASTERIES: '/{region}/v1.4/summoner/{id}/masteries',
    // Stats
    RANKED_STATS: '/{region}/v1.3/stats/by-summoner/{id}/ranked',
    STAT_SUMMARY: '/{region}/v1.3/stats/by-summoner/{id}/summary',
    // Static
    STATIC_CHAMPION: '/static-data/{region}/v1.2/champion',
    STATIC_CHAMPION_ID: '/static-data/{region}/v1.2/champion/{id}',
    STATIC_ITEM: '/static-data/{region}/v1.2/item',
    STATIC_ITEM_ID: '/static-data/{region}/v1.2/item/{id}',
    STATIC_MASTERY: '/static-data/{region}/v1.2/mastery',
    STATIC_MASTERY_ID: '/static-data/{region}/v1.2/mastery/{id}',
    STATIC_REALM: '/static-data/{region}/v1.2/realm',
    STATIC_VERSIONS: '/static-data/{region}/v1.2/versions',
    STATIC_RUNE: '/static-data/{region}/v1.2/rune',
    STATIC_RUNE_ID: '/static-data/{region}/v1.2/rune/{id}',
    STATIC_SUMMONER_SPELL: '/static-data/{region}/v1.2/summoner-spell',
    STATIC_SUMMONER_SPELL_ID: '/static-data/{region}/v1.2/summoner-spell/{id}',
    // Team
    TEAM_BY_SUMMONER: '/{region}/v2.4/team/by-summoner/{id}',
    TEAM_ID: '/{region}/v2.4/team/{id}'
  }
}